---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-pull-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson:  "{{ .pullsecret | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: pullsecret
      remoteRef:
        key: paasis/data/cluster/paasis-dev/common/harbor-access